name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCR_REGION: asia.gcr.io
  IMAGE_NAME: open-webui

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker ${{ env.GCR_REGION }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy open-webui \
            --image ${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --set-env-vars="DB_HOST=${{ secrets.DB_HOST }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_NAME=${{ secrets.DB_NAME }},SCHOOL_NAME=${{ vars.SCHOOL_NAME }}" \
            --add-cloudsql-instances ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
