name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동으로 워크플로우를 실행할 수 있는 옵션 추가

env:
  PROJECT_ID: [openwebui-459316]  # GCP 프로젝트 ID 입력
  REGION: asia-northeast3  # 서울 리전 (필요에 따라 변경)
  SERVICE_NAME: open-webui  # Cloud Run 서비스 이름

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Docker to use gcloud command-line tool
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
        
    - name: Build and tag Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/open-webui-repo/open-webui:${{ github.sha }} .
        docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/open-webui-repo/open-webui:${{ github.sha }} ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/open-webui-repo/open-webui:latest
        
    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/open-webui-repo/open-webui:${{ github.sha }}
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/open-webui-repo/open-webui:latest
        
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/open-webui-repo/open-webui:${{ github.sha }}
        flags: '--add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:open-webui-db'
        env_vars: |
          OLLAMA_BASE_URL=http://localhost:11434
          WEBUI_AUTH=true
          SQLALCHEMY_URL=mysql+pymysql://USERNAME:PASSWORD@/openwebui?unix_socket=/cloudsql/${{ env.PROJECT_ID }}:${{ env.REGION }}:open-webui-db
